### ISSUE TITLE
Does it work for testnet?

### ISSUE THREAD

**Issue by ser** [sbuss/bitmerchant#56]
Does it work for testnet? If not, what should I do to make it working in testnet?

**Comment by sbuss** [comment]
Yup, sure does. See https://github.com/sbuss/bitmerchant/blob/424958e7b11db5040fcf67cbd9c8a628e3a56bda/bitmerchant/network.py#L14-L24 for the testnet constants. You'll have to also include the network constants when instantiating a `Wallet` eg:

```python
from bitmerchant.wallet import Wallet
from bitmerchant.network import BitcoinTestNet

# deserialize a saved wallet
Wallet.deserialize(key, network=BitcoinTestNet)

# from a secret
Wallet.from_master_secret("correct horse battery staple", network=BitcoinTestNet)

# new random wallet on testnet:
Wallet.new_random_wallet(network=BitcoinTestNet)
```

**Comment by ser** [comment]
Thanks for a very clear explanation :-)
